### ISSUE TITLE
nyagos-4.1.6_0 crash

### ISSUE THREAD

**Issue by orz--** [zetamatta/nyagos#165]
I downloaded nyagos-4.1.6_0-amd64.zip

but everytime crash occurred.
see below
************ Panic Occured. ***********
Failed to load lua53: The specified module could not be found.
goroutine 1 [running]:
runtime/debug.Stack(0x3f, 0x0, 0x0)
        c:/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
        c:/go/src/runtime/debug/stack.go:16 +0x29
main.when_panic()
        C:/Users/hymko/Share/GoSrc/nyagos_amd64/main/nyagos.go:91 +0x17b
panic(0x567880, 0xc0420a84e0)
        c:/go/src/runtime/panic.go:458 +0x251
syscall.(*LazyProc).mustFind(0xc04206a9f0)
        c:/go/src/syscall/dll_windows.go:282 +0x71
syscall.(*LazyProc).Call(0xc04206a9f0, 0x0, 0x0, 0x0, 0x8, 0x5981b392fb7a8908, 0x0, 0x580dc0)
        c:/go/src/syscall/dll_windows.go:303 +0x36
_/C_/Users/hymko/Share/GoSrc/nyagos_amd64/lua.New(0xc04202da60)
        C:/Users/hymko/Share/GoSrc/nyagos_amd64/lua/lua.go:34 +0x4f
main.NewNyagosLua(0x638740)
        C:/Users/hymko/Share/GoSrc/nyagos_amd64/main/lua.go:241 +0x3b
main.main()
        C:/Users/hymko/Share/GoSrc/nyagos_amd64/main/nyagos.go:164 +0x2b7
*** Please copy these error message ***
*** And hit ENTER key to quit.      ***

I used nyagos-4.1.5_1-amd64 as well.

**Comment by zetamatta** [comment]
Are there lua53.dll in the same directory with nyagos.exe ?

**Comment by zetamatta** [comment]
Bundled lua53.dll into the new package [4.1.6_1](https://github.com/zetamatta/nyagos/releases/tag/4.1.6_1).

Would you test it ?
