### ISSUE TITLE
lua_e "nyagos.eval('__ls__')" でSEGV

### ISSUE THREAD

**Issue by nocd5** [zetamatta/nyagos#177]
luaスクリプトからnyagos組み込みの`ls`を実行するとパニックを起こします。
3e500b2 混入した不具合のようです。
```
$ lua_e "nyagos.eval('__ls__')"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x18 pc=0x4c79ff]

goroutine 14 [running]:
panic(0x584240, 0x12976030)
        C:/Tools/go32/src/runtime/panic.go:500 +0x331
context.(*valueCtx).Done(0x12be4b00, 0x12b08810)
        <autogenerated>:17 +0x3f
_/I_/Freespace/src/github.com/zetamatta/nyagos/conio.BoxPrint(0x645840, 0x12be4b00, 0x12d80780, 0x1e, 0x1e, 0x644ac0, 0x12b08810, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/conio/box.go:50 +0x577
_/I_/Freespace/src/github.com/zetamatta/nyagos/commands/ls.lsBox(0x645840, 0x12be4b00, 0x0, 0x0, 0x12d07000, 0x1e, 0x20, 0x1, 0x644ac0, 0x12b08810, ...)
        I:/Freespace/src/github.com/zetamatta/nyagos/commands/ls/ls.go:190 +0x439
_/I_/Freespace/src/github.com/zetamatta/nyagos/commands/ls.lsFolder(0x645840, 0x12be4b00, 0x0, 0x0, 0x0, 0x644ac0, 0x12b08810, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/commands/ls/ls.go:325 +0x664
_/I_/Freespace/src/github.com/zetamatta/nyagos/commands/ls.lsCore(0x645840, 0x12be4b00, 0x12cf1a08, 0x0, 0x0, 0x0, 0x644ac0, 0x12b08810, 0x644ac0, 0x12976138, ...)
        I:/Freespace/src/github.com/zetamatta/nyagos/commands/ls/ls.go:346 +0xae
_/I_/Freespace/src/github.com/zetamatta/nyagos/commands/ls.Main(0x645840, 0x12be4b00, 0x12a9a010, 0x0, 0x0, 0x644ac0, 0x12b08810, 0x644ac0, 0x12976138, 0x0, ...)
        I:/Freespace/src/github.com/zetamatta/nyagos/commands/ls/ls.go:497 +0x762
_/I_/Freespace/src/github.com/zetamatta/nyagos/commands.cmd_ls(0x645840, 0x12be4b00, 0x12d80690, 0x12a9a010, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/commands/ls.go:21 +0xf2
_/I_/Freespace/src/github.com/zetamatta/nyagos/commands.Exec(0x645840, 0x12be4b00, 0x12d80690, 0x12cf1bf4, 0x6, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/commands/commands.go:37 +0x2a1
main.main.func1(0x645840, 0x12be4b00, 0x12d80690, 0x6, 0x66e120, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/main/nyagos.go:132 +0x42
_/I_/Freespace/src/github.com/zetamatta/nyagos/alias.hook(0x645840, 0x12be4b00, 0x12d80690, 0xff, 0x4290e8, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/alias/alias.go:148 +0xfe
_/I_/Freespace/src/github.com/zetamatta/nyagos/interpreter.(*Interpreter).spawnvp_noerrmsg(0x12d80690, 0x645840, 0x12be4b00, 0x593e00, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/interpreter/interpreter.go:162 +0x71
_/I_/Freespace/src/github.com/zetamatta/nyagos/interpreter.(*Interpreter).SpawnvpContext(0x12d80690, 0x645840, 0x12be4b00, 0x1, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/interpreter/interpreter.go:216 +0x3f
_/I_/Freespace/src/github.com/zetamatta/nyagos/interpreter.(*Interpreter).InterpretContext(0x12d8c780, 0x0, 0x0, 0x12c31446, 0x6, 0x0, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/interpreter/interpreter.go:340 +0x1143
_/I_/Freespace/src/github.com/zetamatta/nyagos/interpreter.(*Interpreter).Interpret(0x12d8c780, 0x12c31446, 0x6, 0x5a0400, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/interpreter/interpreter.go:231 +0x45
main.cmdEval.func1(0x331c6eac, 0x12c31446, 0x6, 0x12b08810)
        I:/Freespace/src/github.com/zetamatta/nyagos/main/lua_cmd.go:271 +0x216
created by main.cmdEval
        I:/Freespace/src/github.com/zetamatta/nyagos/main/lua_cmd.go:273 +0x1b8
exit status 2
```

**Comment by nocd5** [comment]
スタックトレースの内容は異なりますが、`lua_e "nyagos.exe('__ls__')"`も同様に落ちます。
以下は`lua_e "nyagos.exe('__ls__')"`の場合のエラー内容です。
```
$ lua_e "nyagos.exec('__ls__')"
Doc                         appveyor.yml                dos                         license.txt                 make.cmd                    readline
************ Panic Occured. ***********
runtime error: invalid memory address or nil pointer dereference
goroutine 1 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        C:/Tools/go32/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
        C:/Tools/go32/src/runtime/debug/stack.go:16 +0x1a
main.when_panic()
        I:/Freespace/src/github.com/zetamatta/nyagos/main/nyagos.go:91 +0x130
panic(0x584240, 0x12a16030)
        C:/Tools/go32/src/runtime/panic.go:458 +0x40b
context.(*valueCtx).Done(0x12dd11a0, 0x12b0cb60)
        <autogenerated>:17 +0x3f
_/I_/Freespace/src/github.com/zetamatta/nyagos/conio.BoxPrint(0x645840, 0x12dd11a0, 0x12e1e690, 0x1d, 0x1d, 0x6449c0, 0x12b0cb60, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/conio/box.go:50 +0x577
_/I_/Freespace/src/github.com/zetamatta/nyagos/commands/ls.lsBox(0x645840, 0x12dd11a0, 0x0, 0x0, 0x12c2d300, 0x1d, 0x20, 0x1, 0x6449c0, 0x12b0cb60, ...)
        I:/Freespace/src/github.com/zetamatta/nyagos/commands/ls/ls.go:190 +0x439
_/I_/Freespace/src/github.com/zetamatta/nyagos/commands/ls.lsFolder(0x645840, 0x12dd11a0, 0x0, 0x0, 0x0, 0x6449c0, 0x12b0cb60, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/commands/ls/ls.go:325 +0x664
_/I_/Freespace/src/github.com/zetamatta/nyagos/commands/ls.lsCore(0x645840, 0x12dd11a0, 0x12ded134, 0x0, 0x0, 0x0, 0x6449c0, 0x12b0cb60, 0x644ac0, 0x12a32100, ...)
        I:/Freespace/src/github.com/zetamatta/nyagos/commands/ls/ls.go:346 +0xae
_/I_/Freespace/src/github.com/zetamatta/nyagos/commands/ls.Main(0x645840, 0x12dd11a0, 0x12a32170, 0x0, 0x0, 0x6449c0, 0x12b0cb60, 0x644ac0, 0x12a32100, 0x0, ...)
        I:/Freespace/src/github.com/zetamatta/nyagos/commands/ls/ls.go:497 +0x762
_/I_/Freespace/src/github.com/zetamatta/nyagos/commands.cmd_ls(0x645840, 0x12dd11a0, 0x12e1e5a0, 0x12a32170, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/commands/ls.go:21 +0xf2
_/I_/Freespace/src/github.com/zetamatta/nyagos/commands.Exec(0x645840, 0x12dd11a0, 0x12e1e5a0, 0x12ded320, 0x6, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/commands/commands.go:37 +0x2a1
main.main.func1(0x645840, 0x12dd11a0, 0x12e1e5a0, 0x6, 0x66e120, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/main/nyagos.go:132 +0x42
_/I_/Freespace/src/github.com/zetamatta/nyagos/alias.hook(0x645840, 0x12dd11a0, 0x12e1e5a0, 0x8, 0x12a32158, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/alias/alias.go:148 +0xfe
_/I_/Freespace/src/github.com/zetamatta/nyagos/interpreter.(*Interpreter).spawnvp_noerrmsg(0x12e1e5a0, 0x645840, 0x12dd11a0, 0x0, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/interpreter/interpreter.go:162 +0x71
_/I_/Freespace/src/github.com/zetamatta/nyagos/interpreter.(*Interpreter).SpawnvpContext(0x12e1e5a0, 0x645840, 0x12dd11a0, 0x1, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/interpreter/interpreter.go:216 +0x3f
_/I_/Freespace/src/github.com/zetamatta/nyagos/interpreter.(*Interpreter).InterpretContext(0x12e164b0, 0x0, 0x0, 0x12da0496, 0x6, 0x0, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/interpreter/interpreter.go:340 +0x1143
_/I_/Freespace/src/github.com/zetamatta/nyagos/interpreter.(*Interpreter).Interpret(0x12e164b0, 0x12da0496, 0x6, 0x6, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/interpreter/interpreter.go:231 +0x45
main.cmdExec(0x333ad074, 0x33342a30)
        I:/Freespace/src/github.com/zetamatta/nyagos/main/lua_cmd.go:247 +0xa1d
syscall.Syscall6(0x68d02b00, 0x6, 0x333ad074, 0x1, 0x1, 0x0, 0x0, 0x0, 0x12c3d890, 0x12da0438, ...)
        C:/Tools/go32/src/runtime/syscall_windows.go:174 +0x4a
syscall.(*Proc).Call(0x12a456c0, 0x12cb5ce0, 0x6, 0x6, 0x20, 0x57aa40, 0x0, 0x0)
        C:/Tools/go32/src/syscall/dll_windows.go:157 +0x647
syscall.(*LazyProc).Call(0x12a84540, 0x12cb5ce0, 0x6, 0x6, 0x644ec0, 0x12da0438, 0x0, 0x0)
        C:/Tools/go32/src/syscall/dll_windows.go:304 +0x54
_/I_/Freespace/src/github.com/zetamatta/nyagos/lua.Lua.Call(0x333ad074, 0x1, 0x1, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/lua/lua.go:250 +0xb7
main.NyagosCallLua(0x333ad074, 0x12e164b0, 0x1, 0x1, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/main/lua.go:38 +0x67
main.(*LuaBinaryChank).Call(0x12a458b0, 0x645840, 0x12cb5ba0, 0x12e164b0, 0x12a689d4, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/main/lua_cmd.go:84 +0x5a2
_/I_/Freespace/src/github.com/zetamatta/nyagos/alias.hook(0x645840, 0x12cb5ba0, 0x12e164b0, 0x8, 0x12ccc7b0, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/alias/alias.go:150 +0x13b
_/I_/Freespace/src/github.com/zetamatta/nyagos/interpreter.(*Interpreter).spawnvp_noerrmsg(0x12e164b0, 0x645840, 0x12cb5ba0, 0x0, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/interpreter/interpreter.go:162 +0x71
_/I_/Freespace/src/github.com/zetamatta/nyagos/interpreter.(*Interpreter).SpawnvpContext(0x12e164b0, 0x645840, 0x12cb5ba0, 0x1, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/interpreter/interpreter.go:216 +0x3f
_/I_/Freespace/src/github.com/zetamatta/nyagos/interpreter.(*Interpreter).InterpretContext(0x12a2e3c0, 0x645840, 0x12d13640, 0x12b9b4e0, 0x1d, 0x0, 0x0, 0x0)
        I:/Freespace/src/github.com/zetamatta/nyagos/interpreter/interpreter.go:340 +0x1143
main.main()
        I:/Freespace/src/github.com/zetamatta/nyagos/main/nyagos.go:231 +0xe04
*** Please copy these error message ***
*** And hit ENTER key to quit.      ***
```

**Comment by zetamatta** [comment]
Ctrl-C チェック用に導入した context.Context 引数が内容が無効の時にも使われていたようです。

eval で使う場合などは nil を無効値扱いとしてセットしていたのですが、使う際、なぜか != nil で判別できていませんでした。
その原因はよくわかりませんが、とりあえず nil ではなく、特に機能しないインスタンス（context.Background()の値）を代替にセットするようにしました。

以上、よろしくお願いいたします。

**Comment by nocd5** [comment]
ありがとうございます。
96a0708 で修正されていること確認しました。
