### ISSUE TITLE
Typed `cd` and Ctrl-O(filename-completion) causes panic

### ISSUE THREAD

**Issue by zetamatta** [zetamatta/nyagos#204]
- Current directory is the shared folder between the guest os and the host-os of vmware.
- Windows is 64bit and program is for amd64.
- Not anywhere panic occures but some directory always it occures. 
- This is the stack trace.

```
% cd
runtime: setevent failed; errno=6
fatal error: runtime.semawakeup

runtime stack:
runtime.throw(0x5e49fe, 0x12)
        c:/go/src/runtime/panic.go:596 +0x9c
runtime.semawakeup.func1()
        c:/go/src/runtime/os_windows.go:495 +0x98
runtime.systemstack(0x5ed4e8)
        c:/go/src/runtime/asm_amd64.s:343 +0xb5
runtime.semawakeup(0xc04208dc00)
        c:/go/src/runtime/os_windows.go:496 +0x53
runtime.notewakeup(0xc04208dd08)
        c:/go/src/runtime/lock_sema.go:147 +0x67
runtime.startm(0xc042016000, 0x6c3800)
        c:/go/src/runtime/proc.go:1713 +0xe4
runtime.handoffp(0xc042016000)
        c:/go/src/runtime/proc.go:1725 +0x5c
runtime.retake(0xd60a63d3614, 0x0)
        c:/go/src/runtime/proc.go:3909 +0x164
runtime.sysmon()
        c:/go/src/runtime/proc.go:3836 +0x1f1
runtime.mstart1()
        c:/go/src/runtime/proc.go:1179 +0x116
runtime.mstart()
        c:/go/src/runtime/proc.go:1149 +0x6b

goroutine 1 [syscall, locked to thread]:
syscall.Syscall6(0x7ff9c91619c0, 0x5, 0x370, 0xc0423b6c00, 0x200, 0xc0420ef04c,0x0, 0x0, 0x6, 0x3, ...)
        c:/go/src/runtime/syscall_windows.go:174 +0x6b
syscall.ReadFile(0x370, 0xc0423b6c00, 0x200, 0x200, 0xc0420ef04c, 0x0, 0xc0420ef068, 0xc0420ef060)
        c:/go/src/syscall/zsyscall_windows.go:311 +0xe6
syscall.Read(0x370, 0xc0423b6c00, 0x200, 0x200, 0xc0420ef0c0, 0x40ec2c, 0x100000000000000)
        c:/go/src/syscall/syscall_windows.go:296 +0x6f
os.(*File).read(0xc042004088, 0xc0423b6c00, 0x200, 0x200, 0x0, 0x0, 0x0)
        c:/go/src/os/file_windows.go:289 +0xd0
os.(*File).Read(0xc042004088, 0xc0423b6c00, 0x200, 0x200, 0x427ff5, 0xc000000008, 0xc042202ec0)
        c:/go/src/os/file.go:101 +0x7d
bytes.(*Buffer).ReadFrom(0xc0420ef1b0, 0x6a79a0, 0xc042004088, 0xc0423b6c00, 0x0, 0x200)
        c:/go/src/bytes/buffer.go:179 +0x167
io/ioutil.readAll(0x6a79a0, 0xc042004088, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/io/ioutil/ioutil.go:33 +0x157
io/ioutil.ReadAll(0x6a79a0, 0xc042004088, 0x296918, 0xc0421f1620, 0x13, 0xc04200 4098, 0x1)
        c:/go/src/io/ioutil/ioutil.go:42 +0x45
_/C_/Users/hymko/go/nyagos/mains.cmdEval(0x296918, 0x2270e40)
        C:/Users/hymko/go/nyagos/mains/lua_cmd.go:276 +0x25a
syscall.Syscall6(0x70402bd0, 0x6, 0x296918, 0x1, 0x1, 0x0, 0x0, 0x0, 0xc0420ef650, 0xc0420ef648, ...)
        c:/go/src/runtime/syscall_windows.go:174 +0x6b
syscall.(*Proc).Call(0xc042084cc0, 0xc0423a00f0, 0x6, 0x6, 0x30, 0x5ab0c0, 0x1, 0xc0423a00f0)
        c:/go/src/syscall/dll_windows.go:157 +0x6b0
syscall.(*LazyProc).Call(0xc0420413e0, 0xc0423a00f0, 0x6, 0x6, 0xc04212a000, 0xc04212a000, 0x0, 0x0)
        c:/go/src/syscall/dll_windows.go:303 +0x66
_/C_/Users/hymko/go/nyagos/lua.Lua.Call(0x296918, 0x1, 0x1, 0x0, 0x0)
        C:/Users/hymko/go/nyagos/lua/lua.go:243 +0xbf
_/C_/Users/hymko/go/nyagos/mains.(*KeyLuaFuncT).Call(0xc042085a60, 0xc0423e89a0,0xc00000000f)
        C:/Users/hymko/go/nyagos/mains/lua_bindkey.go:177 +0x771
_/C_/Users/hymko/go/nyagos/readline.(*Editor).ReadLine(0xc04229bd40, 0x6a9160, 0xc0423d9d10, 0x0, 0x0, 0x0, 0x0)
        C:/Users/hymko/go/nyagos/readline/readline.go:230 +0x605
_/C_/Users/hymko/go/nyagos/mains.(*CmdStreamConsole).ReadLine(0xc042316a50, 0x6a9160, 0xc0423d9d10, 0xc04227d9f0, 0x5c7f20, 0xc0422c60c0, 0x6a9160)
        C:/Users/hymko/go/nyagos/mains/stream.go:80 +0xe2
_/C_/Users/hymko/go/nyagos/mains.Main(0x0, 0x0)
        C:/Users/hymko/go/nyagos/mains/nyagos.go:214 +0x88d
main.main()
        C:/Users/hymko/go/nyagos/nyagos.go:37 +0xcb

goroutine 5 [syscall]:
os/signal.signal_recv(0x0)
        c:/go/src/runtime/sigqueue.go:116 +0x10b
os/signal.loop()
        c:/go/src/os/signal/signal_unix.go:22 +0x29
created by os/signal.init.1
        c:/go/src/os/signal/signal_unix.go:28 +0x48

goroutine 6 [chan receive]:
github.com/zetamatta/go-getch.ctrlCHandler(0xc042010660)
        C:/Users/hymko/go/src/github.com/zetamatta/go-getch/ctrlc.go:9 +0x6f
created by github.com/zetamatta/go-getch.DisableCtrlC
        C:/Users/hymko/go/src/github.com/zetamatta/go-getch/ctrlc.go:34 +0xbc

goroutine 21 [syscall, locked to thread]:
syscall.Syscall6(0x7ff9c91619c0, 0x5, 0x378, 0xc04239fe00, 0x200, 0xc04202f6bc,0x0, 0x0, 0x4, 0x3, ...)
        c:/go/src/runtime/syscall_windows.go:174 +0x6b
syscall.ReadFile(0x378, 0xc04239fe00, 0x200, 0x200, 0xc04202f6bc, 0x0, 0xc04202f6d8, 0xc04202f6d0)
        c:/go/src/syscall/zsyscall_windows.go:311 +0xe6
syscall.Read(0x378, 0xc04239fe00, 0x200, 0x200, 0x450a62, 0x40ec2c, 0x5ed280)
        c:/go/src/syscall/syscall_windows.go:296 +0x6f
os.(*File).read(0xc0420040c0, 0xc04239fe00, 0x200, 0x200, 0x0, 0x0, 0x0)
        c:/go/src/os/file_windows.go:289 +0xd0
os.(*File).Read(0xc0420040c0, 0xc04239fe00, 0x200, 0x200, 0x427ff5, 0xc000000008, 0xc0423a6300)
        c:/go/src/os/file.go:101 +0x7d
bytes.(*Buffer).ReadFrom(0xc04202f820, 0x6a79a0, 0xc0420040c0, 0xc04239fe00, 0x0, 0x200)
        c:/go/src/bytes/buffer.go:179 +0x167
io/ioutil.readAll(0x6a79a0, 0xc0420040c0, 0x200, 0x0, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/io/ioutil/ioutil.go:33 +0x157
io/ioutil.ReadAll(0x6a79a0, 0xc0420040c0, 0xc0421e846b, 0x3, 0x0, 0x0, 0x0)
        c:/go/src/io/ioutil/ioutil.go:42 +0x45
_/C_/Users/hymko/go/nyagos/commands.cmd_box(0x6a9160, 0xc0423a0d50, 0xc0420990e0, 0xc0421e8fc0, 0x1, 0x1)
        C:/Users/hymko/go/nyagos/commands/box.go:17 +0x54
_/C_/Users/hymko/go/nyagos/commands.Exec(0x6a9160, 0xc0423a0d50, 0xc0420990e0, 0x8, 0x3, 0xc042056d40, 0x3)
        C:/Users/hymko/go/nyagos/commands/commands.go:38 +0x163
_/C_/Users/hymko/go/nyagos/mains.Main.func1(0x6a9160, 0xc0423a0d50, 0xc0420990e0, 0x3, 0x6e3740, 0x0, 0x10)
        C:/Users/hymko/go/nyagos/mains/nyagos.go:155 +0x46
_/C_/Users/hymko/go/nyagos/alias.hook(0x6a9160, 0xc0423a0d50, 0xc0420990e0, 0xc0421e8fb0, 0x0, 0xc0421ec000, 0x0)
        C:/Users/hymko/go/nyagos/alias/alias.go:149 +0x127
_/C_/Users/hymko/go/nyagos/shell.(*Cmd).spawnvp_noerrmsg(0xc0420990e0, 0x6a9160,0xc0423a0d50, 0x0, 0x0, 0xc0421e8fb0)
        C:/Users/hymko/go/nyagos/shell/interpreter.go:165 +0x5e
_/C_/Users/hymko/go/nyagos/shell.(*Cmd).SpawnvpContext(0xc0420990e0, 0x6a9160, 0xc0423a0d50, 0x0, 0x1, 0xc0421e8fb0)
        C:/Users/hymko/go/nyagos/shell/interpreter.go:219 +0x61
_/C_/Users/hymko/go/nyagos/shell.(*Cmd).InterpretContext(0xc042098d20, 0x6a9120,0xc04200e350, 0xc0421f1620, 0x13, 0x0, 0x0, 0x0)
        C:/Users/hymko/go/nyagos/shell/interpreter.go:352 +0xaa2
_/C_/Users/hymko/go/nyagos/shell.(*Cmd).Interpret(0xc042098d20, 0xc0421f1620, 0x13, 0xc0421e8460, 0x0, 0xc0420c114b)
        C:/Users/hymko/go/nyagos/shell/interpreter.go:234 +0x5e
_/C_/Users/hymko/go/nyagos/mains.cmdEval.func1(0x296918, 0xc0421f1620, 0x13, 0xc042004098)
        C:/Users/hymko/go/nyagos/mains/lua_cmd.go:272 +0x247
created by _/C_/Users/hymko/go/nyagos/mains.cmdEval
        C:/Users/hymko/go/nyagos/mains/lua_cmd.go:274 +0x240

goroutine 22 [runnable]:
_/C_/Users/hymko/go/nyagos/shell.(*Cmd).InterpretContext.func2(0xc0421e8f20, 0xc04221c0a0, 0xc0421e8f30, 0x6a9160, 0xc0423a0cf0, 0xc042098f00)
        C:/Users/hymko/go/nyagos/shell/interpreter.go:360
created by _/C_/Users/hymko/go/nyagos/shell.(*Cmd).InterpretContext
        C:/Users/hymko/go/nyagos/shell/interpreter.go:375 +0xb79
exit status 2
```

**Comment by zetamatta** [comment]
This crash occures when Japanese filenames exist.

**Comment by zetamatta** [comment]
Not on virtual machine, crash occurs

**Comment by zetamatta** [comment]
Stop using OS-pipeline to give options to select. 

    local result = nyagos.eval(" (lua alias to output choces) | box")

Now new function `nyagos.box` is used.

    local result = nyagos.box( { choices,... } )
