### ISSUE TITLE
Panic: `lnk . ~`

### ISSUE THREAD

**Issue by zetamatta** [zetamatta/nyagos#224]
The stacktrace is below:

```
$ lnk . ~
************ Panic Occured. ***********
runtime error: index out of range
goroutine 1 [running]:
runtime/debug.Stack(0x22, 0x0, 0x0)
        c:/go/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        c:/go/src/runtime/debug/stack.go:16 +0x1a
main.when_panic()
        C:/Users/Hayama/go/386-nyagos/nyagos.go:19 +0x10a
panic(0x569a40, 0x64a428)
        c:/go/src/runtime/panic.go:489 +0x22a
_/C_/Users/Hayama/go/386-nyagos/shell.makeCmdline(0x119156c0, 0x5, 0x8, 0x1192ca
60, 0x3, 0x4, 0x1f, 0x11930fc0)
        C:/Users/Hayama/go/386-nyagos/shell/interpreter.go:158 +0x374
_/C_/Users/Hayama/go/386-nyagos/shell.(*Cmd).spawnvp_noerrmsg(0x119b1d10, 0x6368
e0, 0x1192cd80, 0x1, 0x1192cd80, 0x4bb306)
        C:/Users/Hayama/go/386-nyagos/shell/interpreter.go:210 +0x16a
_/C_/Users/Hayama/go/386-nyagos/shell.(*Cmd).SpawnvpContext(0x119b1d10, 0x6368e0
, 0x1192cd80, 0x660aa8, 0x559ce0, 0x11930fc0)
        C:/Users/Hayama/go/386-nyagos/shell/interpreter.go:243 +0x35
_/C_/Users/Hayama/go/386-nyagos/shell.(*Cmd).InterpretContext(0x115d4870, 0x6368
e0, 0x1190fd60, 0x119301c0, 0x8, 0x0, 0x0, 0x0)
        C:/Users/Hayama/go/386-nyagos/shell/interpreter.go:371 +0x66a
_/C_/Users/Hayama/go/386-nyagos/mains.Main(0x0, 0x0)
        C:/Users/Hayama/go/386-nyagos/mains/nyagos.go:252 +0x70b
main.main()
        C:/Users/Hayama/go/386-nyagos/nyagos.go:37 +0xae
*** Please copy these error message ***
*** And hit ENTER key to quit.      ***
```

`lnk` is JScript which makes Windows' shortcut.

```
if( WScript.Arguments.length == 1  ){
    var wshShell = new ActiveXObject("WScript.Shell");
    var lnkSrc = wshShell.CreateShortcut(WScript.Arguments.Unnamed(0));
    if( lnkSrc == null ){
        WScript.Echo("Fail to create ShortCut Object");
    } else {
        WScript.Echo( "    " + lnkSrc + "\n<-- " + lnkSrc.TargetPath ); 
    }
    WScript.Quit(1);
}

if( WScript.Arguments.length < 2 ){
    WScript.Echo(
        "Usage: cscript lnk.js FILENAME SHORTCUT {Option=Value}... make shortcut\n" +
        "       cscript lnk.js SHORTCUT          ... print shortcut-target")
    WScript.Quit(1);
}

var fsObj = new ActiveXObject("Scripting.FileSystemObject");
var src = fsObj.GetAbsolutePathName(WScript.Arguments.Item(0));
var dst = fsObj.GetAbsolutePathName(WScript.Arguments.Item(1));

if( fsObj.FolderExists(dst) ){
    dst = fsObj.BuildPath(dst,fsObj.GetFileName(src));
}
if( dst.length >= 4 && dst.substring(dst.length-4) != ".lnk" ){
    dst += ".lnk";
}
var wshShell=new ActiveXObject("WScript.Shell");
var shortcut1=wshShell.CreateShortcut(dst);

if( shortcut1 == null ){
    WScript.Echo("Fail to create ShortCut Object");
    WScript.Quit(1);
}
shortcut1.TargetPath=src;

if( WScript.Arguments.length >= 3 ){
    for(var i=2 ; i < WScript.Arguments.length ; i++ ){
        var equation = WScript.Arguments.Item(i);
        var pos = equation.indexOf("=",0);
        if( pos >= 0 ){
            equation="shortcut1." + equation.substring(0,pos) + "=\"" +
                    equation.substring(pos+1).replace(/\\/g,"\\\\") + "\"";
            WScript.Echo(equation);
            eval(equation);
        }else{
            WScript.Echo("Equal(=) not found: " + equation)
        }
    }
}
shortcut1.Save()
WScript.Echo("    " + src + "\n--> " + dst);
WScript.Quit(0)
```

**Comment by zetamatta** [comment]
This bug did not exist on the released executable.
