### ISSUE TITLE
.nyagosに空文字のグローバル変数がある場合 pipeを使うと落ちる

### ISSUE THREAD

**Issue by nocd5** [zetamatta/nyagos#232]
## 環境

- nyagos : 845a1e7
- OS : windows 7 pro
- go : 1.8.3
- lua : 5.3.4

## 症状

`.nyagos`内に空文字の変数があった場合pipeで落ちます。
以下の場合は問題ありません
- `HOGE=nil`
- `share.HOGE = ''`

## 再現パターン

設定ファイル
```lua
HOGE = ''
```

再現コマンド
```
$ pwd | clip
```

エラーログ
```
Nihongo Yet Another GOing Shell 4.2.0_1-6-g845a1e7-amd64 by go1.8.3 & Lua 5.3
(c) 2014-2017 NYAOS.ORG <http://www.nyaos.org>
[C:/Tools/gopath/src/github.com/zetamatta/nyagos]
$ pwd | clip
************ Panic Occured. ***********
runtime error: index out of range
goroutine 1 [running]:
runtime/debug.Stack(0x22, 0x0, 0x0)
        C:/Tools/Go64/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
        C:/Tools/Go64/src/runtime/debug/stack.go:16 +0x29
main.when_panic()
        C:/Tools/gopath/src/github.com/zetamatta/nyagos/nyagos.go:19 +0x17b
panic(0x5badc0, 0x6cac50)
        C:/Tools/Go64/src/runtime/panic.go:489 +0x2dd
github.com/zetamatta/nyagos/lua.Lua.PushBytes(0xa0dd88, 0x6f1768, 0x0, 0x0)
        C:/Tools/gopath/src/github.com/zetamatta/nyagos/lua/push.go:40 +0x9e
github.com/zetamatta/nyagos/lua.TRawString.Push(0x6f1768, 0x0, 0x0, 0xa0dd88, 0x
ffffffffffffffff)
        C:/Tools/gopath/src/github.com/zetamatta/nyagos/lua/to.go:96 +0x50
github.com/zetamatta/nyagos/lua.(*TRawString).Push(0xc042298900, 0xa0dd88, 0x6b6
100)
        <autogenerated>:95 +0x70
github.com/zetamatta/nyagos/lua.Lua.CloneTo.func1(0xb27bc8, 0x0, 0x0)
        C:/Tools/gopath/src/github.com/zetamatta/nyagos/lua/clone.go:28 +0x172
github.com/zetamatta/nyagos/lua.Lua.ForInDo(0xb27bc8, 0xfffffffffffffffe, 0xc042
2d7ad0, 0x1, 0xc042117e30)
        C:/Tools/gopath/src/github.com/zetamatta/nyagos/lua/to.go:215 +0x7c
github.com/zetamatta/nyagos/lua.Lua.CloneTo(0xb27bc8, 0xa0dd88, 0x0, 0x0)
        C:/Tools/gopath/src/github.com/zetamatta/nyagos/lua/clone.go:31 +0xcc
github.com/zetamatta/nyagos/mains.onFork(0xc042043b80, 0x1, 0x0)
        C:/Tools/gopath/src/github.com/zetamatta/nyagos/mains/nyagos.go:146 +0x8
7
github.com/zetamatta/nyagos/shell.(*Cmd).InterpretContext(0xc0420434a0, 0x6b7200
, 0xc0421c5680, 0xc042105a20, 0xa, 0x0, 0x0, 0x0)
        C:/Tools/gopath/src/github.com/zetamatta/nyagos/shell/interpreter.go:377
 +0x97f
github.com/zetamatta/nyagos/shell.(*Cmd).Loop(0xc0420434a0, 0x6b6d80, 0xc042002a
60, 0x0, 0x0)
        C:/Tools/gopath/src/github.com/zetamatta/nyagos/shell/loop.go:46 +0x25a
github.com/zetamatta/nyagos/mains.Main(0x0, 0x0)
        C:/Tools/gopath/src/github.com/zetamatta/nyagos/mains/nyagos.go:239 +0x5
48
main.main()
        C:/Tools/gopath/src/github.com/zetamatta/nyagos/nyagos.go:37 +0xcb
*** Please copy these error message ***
*** And hit ENTER key to quit.      ***
```

**Comment by zetamatta** [comment]
ご報告ありがとうございます。現象、こちらでも確認しました。
調査・修正に着手します。

**Comment by zetamatta** [comment]
本件、発生条件を見つけるのが大変だったのではないかと思います（普通の人だったら投げてしまいそう）。ご確認およびご報告、心より感謝いたします。

おかげで、不具合の原因がすぐ分かりましたので、急ぎ、修正しました。

原因は、Lua に Go 言語の文字列のアドレスを引き渡すのに `&foo[0]` としていた箇所があったためでした（Go では `foo != &foo[0]` ）。0 文字の時、これが配列上限をオーバーするということで、クラッシュの原因となっていました。

パイプラインは直接の原因ではありませんが、パイプライン作成する時に Lua のグローバル変数の「フルコピー」が Lua のインスタンス間で行われるため、本不具合を踏むトリガーになっていたようです。

対応として、長さチェックを入れ、0文字の時は特別扱いするようにしました。

ソースは既に修正ですが、問題自体はクリティカルなので、バイナリにも早いうちに反映させたいと思います。

**Comment by zetamatta** [comment]
修正版のバイナリを公開しました。

[Release 4.2.0_2 · zetamatta/nyagos](https://github.com/zetamatta/nyagos/releases/tag/4.2.0_2)

**Comment by nocd5** [comment]
迅速な対応ありがとうございます。 ad02f78 で修正されている事を確認しました。
久しぶりにnyagos更新し設定ファイルからグローバルな`share`テーブルを外している過程で
偶然踏んだため
再現パターンもすぐ見つけることができ、原因究明のお役に立てて良かったです。
