### ISSUE TITLE
type `~dbgview` -> crash.

### ISSUE THREAD

**Issue by zetamatta** [zetamatta/nyagos#375]
```
$ ~dbgview

************ Panic Occurred. ***********
runtime error: index out of range [7] with length 7
goroutine 1 [running]:
runtime/debug.Stack(0x8f50c0, 0xc0002355a0, 0xc0004f13d0)
        C:/go/src/runtime/debug/stack.go:24 +0xa4
github.com/zetamatta/nyagos/frame.PanicHandler()
        C:/Users/hymko/go/src/github.com/zetamatta/nyagos/frame/misc.go:50 +0x19
3
panic(0x82d5e0, 0xc000170e40)
        C:/go/src/runtime/panic.go:679 +0x1c0
github.com/zetamatta/nyagos/shell.string2word(0xc0004f1710, 0x8, 0x0, 0x40, 0xc0
004f1710)
        C:/Users/hymko/go/src/github.com/zetamatta/nyagos/shell/parser.go:138 +0
x1822
github.com/zetamatta/nyagos/shell.parse1.func1(0x85e368, 0x1)
        C:/Users/hymko/go/src/github.com/zetamatta/nyagos/shell/parser.go:315 +0
x491
github.com/zetamatta/nyagos/shell.parse1(0x8f8aa0, 0xc000162ee0, 0xc0004c50c0, 0
x8, 0x0, 0x8, 0x7cdf40, 0xc0002542d0, 0xbacb68)
        C:/Users/hymko/go/src/github.com/zetamatta/nyagos/shell/parser.go:555 +0
xc03
github.com/zetamatta/nyagos/shell.parse(0x8f8aa0, 0xc000162ee0, 0xc0004c50c0, 0x
8, 0x100000000000001, 0x0, 0xc, 0xc0004c50d0, 0x410)
        C:/Users/hymko/go/src/github.com/zetamatta/nyagos/shell/parser.go:578 +0
x54
github.com/zetamatta/nyagos/shell.(*Shell).Interpret(0xc00011a780, 0x8fc6e0, 0xc
00031e400, 0xc0004c50c0, 0x8, 0xc0003a6530, 0x8, 0x0)
        C:/Users/hymko/go/src/github.com/zetamatta/nyagos/shell/interpreter.go:3
87 +0x79
github.com/zetamatta/nyagos/shell.(*Shell).Loop(0xc00011a780, 0x8fc7a0, 0xc00038
4570, 0x8f8aa0, 0xc000162ee0, 0x0, 0x0, 0x0)
        C:/Users/hymko/go/src/github.com/zetamatta/nyagos/shell/loop.go:106 +0x2
b1
github.com/zetamatta/nyagos/shell.(*Shell).ForEver(0xc00011a780, 0x8fc7a0, 0xc00
0384570, 0x8f8aa0, 0xc000162ee0)
        C:/Users/hymko/go/src/github.com/zetamatta/nyagos/shell/loop.go:132 +0x6
7
github.com/zetamatta/nyagos/mains.Main(0x0, 0x0)
        C:/Users/hymko/go/src/github.com/zetamatta/nyagos/mains/nyagos.go:210 +0
x5c8
github.com/zetamatta/nyagos/frame.Start(0x87e378, 0x0, 0x0)
        C:/Users/hymko/go/src/github.com/zetamatta/nyagos/frame/misc.go:37 +0x1a
f
main.main()
        C:/Users/hymko/go/src/github.com/zetamatta/nyagos/main.go:17 +0x6f
*** Please copy these error message ***
*** And hit ENTER key to quit.      ***
```

**Comment by zetamatta** [comment]
Fixed.
