### ISSUE TITLE
crashed with "history -100"

### ISSUE THREAD

**Issue by zetamatta** [zetamatta/nyagos#48]
```
panic: runtime error: slice bounds out of range

goroutine 16 [running]:
runtime.panic(0x50a6c0, 0x5cb40f)
        c:/go/src/pkg/runtime/panic.c:279 +0xe9
_/C_/Users/Hayama/gosrc/nyagos/history.CmdHistory(0x122f2a00, 0x122fa358, 0x0, 0x0)
        C:/Users/Hayama/gosrc/nyagos/history/history.go:232 +0x273
_/C_/Users/Hayama/gosrc/nyagos/commands.Exec(0x122f2a00, 0x122e9700, 0x2d0288, 0x0, 0x554420, 0x0, 0x0)
        C:/Users/Hayama/gosrc/nyagos/commands/commands.go:167 +0x412
_/C_/Users/Hayama/gosrc/nyagos/alias.Hook(0x122f2a00, 0x0, 0x2d0288, 0x0, 0x0, 0x0, 0x0)
        C:/Users/Hayama/gosrc/nyagos/alias/alias.go:87 +0xca
```

**Comment by zetamatta** [comment]
Fixed!
