### ISSUE TITLE
Panic at "ls -ltr" on Virtual Machine of Windows8-64bit.

### ISSUE THREAD

**Issue by zetamatta** [zetamatta/nyagos#54]
```
$ ls -ltr
-rw-Exception 0xc0000006 0x8 0x4aa690 0x4aa690
PC=0x4aa690

time.Unix(0x0, 0x0, 0x8a4bdea8, 0x13ce11ff, 0x1211efe0, 0x12, 0x1211efe0, 0x0)
        c:/go/src/time/time.go:969
os.(*fileStat).ModTime(0x12154140, 0x0, 0x0, 0x0, 0x0)
        c:/go/src/os/types_windows.go:49 +0x94
_/C_/Users/Hayama/GoSrc/nyagos/commands/ls.lsOneLong(0x549700, 0x1, 0x192e00, 0x
12154140, 0x6f, 0x191d30, 0x120ef030)
        C:/Users/Hayama/GoSrc/nyagos/commands/ls/ls.go:102 +0x2a2
_/C_/Users/Hayama/GoSrc/nyagos/commands/ls.lsLong(0x549700, 0x1, 0x120a4250, 0x1
, 0x1, 0x6f, 0x191d30, 0x120ef030)
        C:/Users/Hayama/GoSrc/nyagos/commands/ls/ls.go:166 +0x9a
_/C_/Users/Hayama/GoSrc/nyagos/commands/ls.lsFolder(0x549700, 0x1, 0x6e, 0x191d3
0, 0x120ef030, 0x0, 0x0)
        C:/Users/Hayama/GoSrc/nyagos/commands/ls/ls.go:246 +0x6ee
_/C_/Users/Hayama/GoSrc/nyagos/commands/ls.lsCore(0x121397e4, 0x0, 0x0, 0x6e, 0x
191d30, 0x120ef030, 0x0, 0x0)
        C:/Users/Hayama/GoSrc/nyagos/commands/ls/ls.go:264 +0x77
_/C_/Users/Hayama/GoSrc/nyagos/commands/ls.Main(0x1211efa8, 0x2, 0x3, 0x191d30,
0x120ef030, 0x0, 0x0)
        C:/Users/Hayama/GoSrc/nyagos/commands/ls/ls.go:384 +0x72f
_/C_/Users/Hayama/GoSrc/nyagos/commands.cmd_ls(0x120bbe00, 0x1211efa0, 0x0, 0x0)

        C:/Users/Hayama/GoSrc/nyagos/commands/ls.go:12 +0x101
_/C_/Users/Hayama/GoSrc/nyagos/commands.Exec(0x120bbe00, 0x120a4118, 0x0, 0x0)
        C:/Users/Hayama/GoSrc/nyagos/commands/commands.go:81 +0x556
_/C_/Users/Hayama/GoSrc/nyagos/alias.hook(0x120bbe00, 0x192f50, 0x0, 0x0)
        C:/Users/Hayama/GoSrc/nyagos/alias/alias.go:82 +0x62
_/C_/Users/Hayama/GoSrc/nyagos/interpreter.(*Interpreter).Interpret(0x120bbd40,
0x1213cea0, 0xb, 0x12139cf4, 0x0, 0x0)
        C:/Users/Hayama/GoSrc/nyagos/interpreter/interpreter.go:147 +0x685
_/C_/Users/Hayama/GoSrc/nyagos/alias.(*AliasFunc).Call(0x120fc0f8, 0x120ba900, 0
x120fc0f8, 0x0, 0x0)
        C:/Users/Hayama/GoSrc/nyagos/alias/alias.go:54 +0x46a
_/C_/Users/Hayama/GoSrc/nyagos/alias.hook(0x120ba900, 0x192f50, 0x0, 0x0)
        C:/Users/Hayama/GoSrc/nyagos/alias/alias.go:97 +0x1fa
_/C_/Users/Hayama/GoSrc/nyagos/interpreter.(*Interpreter).Interpret(0x120ba600,
0x1213c307, 0x7, 0x7, 0x0, 0x0)
        C:/Users/Hayama/GoSrc/nyagos/interpreter/interpreter.go:147 +0x685
main.main()
        C:/Users/Hayama/GoSrc/nyagos/main/nyagos.go:191 +0xe0f

goroutine 5 [syscall, 10 minutes]:
os/signal.loop()
        c:/go/src/os/signal/signal_unix.go:21 +0x21
created by os/signal.initﾂｷ1
        c:/go/src/os/signal/signal_unix.go:27 +0x34

goroutine 6 [chan receive, 10 minutes]:
_/C_/Users/Hayama/GoSrc/nyagos/conio.ctrlCHandler(0x12084ec0)
        C:/Users/Hayama/GoSrc/nyagos/conio/getch.go:55 +0x50
created by _/C_/Users/Hayama/GoSrc/nyagos/conio.DisableCtrlC
        C:/Users/Hayama/GoSrc/nyagos/conio/getch.go:63 +0xc3
eax     0x8a4bdea8
ebx     0x0
ecx     0x64
edx     0x13ce11ff
edi     0x1211ec5c
esi     0x1211efe0
ebp     0x13ce11e4
esp     0x1213944c
eip     0x4aa690
eflags  0x10206
cs      0x23
fs      0x53
gs      0x2b
```

**Comment by zetamatta** [comment]
Close because it has been occured recetly and ls-codes are changed a lot.
