### ISSUE TITLE
panic at Windows7-VM (32bit)

### ISSUE THREAD

**Issue by zetamatta** [zetamatta/nyagos#76]
```
$ make status

Microsoft(R) Program Maintenance Utility Version 10.00.30319.01
Copyright (C) Microsoft Corporation.  All rights reserved.

        start yShowVer.exe  Debug\GENEPORTAL.exe  Debug\SheetTBL.dll  Release\
NEPORTAL.exe  Release\SheetTBL.dll
fatal error: G waiting list is corrupted!

goroutine 1 [running]:
runtime.gothrow(0x575ba8, 0x1c)
        c:/go/src/runtime/panic.go:503 +0x67 fp=0x117accb8 sp=0x117accac
runtime.chanrecv(0x513ba0, 0x11836200, 0x117ace60, 0x466c01, 0x0)
        c:/go/src/runtime/chan.go:414 +0x3c5 fp=0x117acd10 sp=0x117accb8
runtime.chanrecv1(0x513ba0, 0x11836200, 0x117ace60)
        c:/go/src/runtime/chan.go:311 +0x24 fp=0x117acd28 sp=0x117acd10
_/C_/Users/Hayama/GoSrc/nyagos/interpreter.(*Interpreter).Interpret(0x117b9520
0x11856410, 0xb, 0x1, 0x0, 0x0)
        C:/Users/Hayama/GoSrc/nyagos/interpreter/interpreter.go:249 +0xd5a fp=
117ace94 sp=0x117acd28
main.main()
        C:/Users/Hayama/GoSrc/nyagos/main/nyagos.go:209 +0xebe fp=0x117acfcc s
0x117ace94
runtime.main()
        c:/go/src/runtime/proc.go:63 +0xcc fp=0x117acff0 sp=0x117acfcc
runtime.goexit()
        c:/go/src/runtime/asm_386.s:2287 +0x1 fp=0x117acff4 sp=0x117acff0

goroutine 5 [syscall, 2 minutes]:
os/signal.loop()
        c:/go/src/os/signal/signal_unix.go:21 +0x21
created by os/signal.initﾂｷ1
        c:/go/src/os/signal/signal_unix.go:27 +0x34

goroutine 6 [chan receive, 2 minutes]:
_/C_/Users/Hayama/GoSrc/nyagos/conio.ctrlCHandler(0x11798d80)
        C:/Users/Hayama/GoSrc/nyagos/conio/getch.go:55 +0x50
created by _/C_/Users/Hayama/GoSrc/nyagos/conio.DisableCtrlC
        C:/Users/Hayama/GoSrc/nyagos/conio/getch.go:63 +0xc3
<WIN7-32-201303:~>
```

**Comment by zetamatta** [comment]
When the panic does not occur again till 2015.07.08, this issue will be closed.

**Comment by zetamatta** [comment]
Not resolved. X-(

Same error occured.

```
fatal error: G waiting list is corrupted!

goroutine 1 [running]:
runtime.gothrow(0x5759a8, 0x1c)
        c:/go/src/runtime/panic.go:503 +0x67 fp=0x1173ccc0 sp=0x1173ccb4
runtime.chanrecv(0x5139e0, 0x117e1040, 0x1173ce60, 0x466b01, 0x0)
        c:/go/src/runtime/chan.go:414 +0x3c5 fp=0x1173cd18 sp=0x1173ccc0
runtime.chanrecv1(0x5139e0, 0x117e1040, 0x1173ce60)
        c:/go/src/runtime/chan.go:311 +0x24 fp=0x1173cd30 sp=0x1173cd18
_/C_/Users/Hayama/GoSrc/nyagos/interpreter.(*Interpreter).Interpret(0x1174ad00,0x117b4bc0, 0x4, 0x1, 0x0, 0x0)
        C:/Users/Hayama/GoSrc/nyagos/interpreter/interpreter.go:249 +0xcba fp=0x1173ce94 sp=0x1173cd30
main.main()
```

**Comment by zetamatta** [comment]
When the panic does not occur again till 2015.07.10, this issue will be closed.

**Comment by zetamatta** [comment]
Close because it has been occured.
