### ISSUE TITLE
aliasをパイプで繋ぐとクラッシュする

### ISSUE THREAD

**Issue by cagechi** [zetamatta/nyagos#82]
$ alias ls
ls=ls -aoFlh $*

$ alias grep
grep=yagrep -P -i $*

ls|grep → クラッシュします。

NYAGOS 4.0.9_8 + Windows7

上記以外のコマンドでもalias設定すると同様の現象が発生するようです。

**Comment by zetamatta** [comment]
ご報告ありがとうございます。再現しましたので、対応着手します

```
<MARKEDONE:~>
$ alias "ls=ls -aoFlh $*"
<MARKEDONE:~>
$ alias "grep=yagrep -P -i $*"
<MARKEDONE:~>
$ ls | grep
Exception 0xc0000005 0x0 0x38 0x68d05549
PC=0x68d05549
signal arrived during cgo execution

syscall.(*Proc).Call(0x1205e5e0, 0x1209d970, 0x6, 0x6, 0x0, 0x0, 0x0, 0x0)
        C:/Users/hayama/Local/Program Files/go/src/syscall/dll_windows.go:140 +0x65a
syscall.(*LazyProc).Call(0x11fda8a0, 0x1209d970, 0x6, 0x6, 0x1209d9a8, 0x4, 0x0, 0x0)
        C:/Users/hayama/Local/Program Files/go/src/syscall/dll_windows.go:279 +0x5f
_/C_/Users/hayama/GoSrc/nyagos/lua.Lua.Call(0x7631bc, 0x1, 0x1, 0x0, 0x0)
        C:/Users/hayama/GoSrc/nyagos/lua/lua.go:255 +0xc3
main.newArgHook(0x11fbb5f0, 0x12055620, 0x3, 0x4, 0x0, 0x0, 0x0)
        C:/Users/hayama/GoSrc/nyagos/main/lua.go:153 +0x245
_/C_/Users/hayama/GoSrc/nyagos/interpreter.(*Interpreter).Interpret(0x11fbb5f0,0x12077e70, 0xd, 0x1, 0x0, 0x0)
        C:/Users/hayama/GoSrc/nyagos/interpreter/interpreter.go:181 +0x197
_/C_/Users/hayama/GoSrc/nyagos/alias.(*AliasFunc).Call(0x11fb0248, 0x11fbb520, 0x12076ea8, 0x0, 0x0)
        C:/Users/hayama/GoSrc/nyagos/alias/alias.go:54 +0x46a
_/C_/Users/hayama/GoSrc/nyagos/alias.hook(0x11fbb520, 0x557c90, 0x0, 0x0)
        C:/Users/hayama/GoSrc/nyagos/alias/alias.go:88 +0x103
_/C_/Users/hayama/GoSrc/nyagos/interpreter.(*Interpreter).Spawnvp(0x11fbb520, 0x1, 0x0, 0x0)
        C:/Users/hayama/GoSrc/nyagos/interpreter/interpreter.go:149 +0x5a
_/C_/Users/hayama/GoSrc/nyagos/interpreter.(*Interpreter).Interpret(0x12079930,0x12076e90, 0x9, 0x1, 0x0, 0x0)
        C:/Users/hayama/GoSrc/nyagos/interpreter/interpreter.go:234 +0xc75
main.main()
        C:/Users/hayama/GoSrc/nyagos/main/nyagos.go:211 +0xebe

goroutine 5 [syscall]:
os/signal.loop()
        C:/Users/hayama/Local/Program Files/go/src/os/signal/signal_unix.go:21 +0x21
created by os/signal.initﾂｷ1
        C:/Users/hayama/Local/Program Files/go/src/os/signal/signal_unix.go:27 +0x34

goroutine 6 [chan receive]:
_/C_/Users/hayama/GoSrc/nyagos/conio.ctrlCHandler(0x11f98dc0)
        C:/Users/hayama/GoSrc/nyagos/conio/getch.go:55 +0x50
created by _/C_/Users/hayama/GoSrc/nyagos/conio.DisableCtrlC
        C:/Users/hayama/GoSrc/nyagos/conio/getch.go:63 +0xc3
eax     0x8
ebx     0x68d2c33c
ecx     0x7631ec
edx     0x32532444
edi     0x324afad0
esi     0x0
ebp     0x76c838
esp     0x324afa34
eip     0x68d05549
eflags  0x10202
cs      0x23
fs      0x53
gs      0x2b
exit status 2
```

**Comment by zetamatta** [comment]
メモ：alias の無駄な多重展開を削減した分、頻度は減ったが、それでも nyagos.argsfilter がパイプ上で同時に呼ばれている場合あり

```
$ ls | grep m
Enter newArgHook[ls]
Leave newArgHook
Enter newArgHook[grep][m]
Leave newArgHook
Enter newArgHook[findstr][m]
Enter newArgHook[ls][-oF]
Leave newArgHook
Leave newArgHook
```

**Comment by zetamatta** [comment]
- コマンドラインの引数フィルター（`nyagos.argsfilter`）が同時に動作しないようにした
- alias 展開を無駄に多重に行っていた不具合を修正 （「`ls`」→「`ls oF`」→「`ls -oF -oF`」…5回繰り返していた：これでフィルターが同時起動しやすくなっていた）

という二点を修正したところ、現行リビジョン（0db3edcff73426aeecf5d113c1b77128aece0814）時点で、panic が発生しなくなりました。

```
$ ls | grep m
Enter newArgHook[ls]
Leave newArgHook
Enter newArgHook[grep][m]
Leave newArgHook
Enter newArgHook[findstr][m]
Leave newArgHook
Enter newArgHook[ls][-oF]
Leave newArgHook
Doc/               foo.lua*           main/              nyole.dll
Misc/              history/           make.cmd*          readme.md
alias/             hogehoge.cmd*      makeconst.lua*     readme_ja.md
catalog.d/         interpreter/       makeicon.cmd*      specialfolders.js*
commands/          license.txt        nyagos.d/          t/
completion/        lnk.js*            nyagos.exe*
```

近いうちに修正バイナリを公開いたします。

**Comment by cagechi** [comment]
迅速な御対応ありがとうございます。

**Comment by cagechi** [comment]
4.0.9_9にて問題無いことを確認しました。
対応ありがとうございました。
